### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by DwaineGarden** [hackair-project/hackAir-Arduino#10]
Getting my sensor up and running.  I notice an error with the wemos code example.  I could not get it to compile properly without the "char".

// Authentication token, will be acquired during the WiFi setup process
hackair_auth_token[128] = "";

Should be this:

// Authentication token, will be acquired during the WiFi setup process
char hackair_auth_token[128] = "";

**Comment by sakisds** [comment]
Hello, it seems I used the wrong branch when zipping the library for upload. The file from the releases page should now work fine.
