### ISSUE TITLE
The online Hackair map does not update with sensor data

### ISSUE THREAD

**Issue by DwaineGarden** [hackair-project/hackAir-Arduino#11]
I have my device setup and running fine.   When I look at my online profile it has my sensor with updated measurement values perfectly fine.   When I look at the online Hackair map, the sensor is listed but only for the initial sensor creation.   The values are never updated on the map?

If I go back and see my sensor measurements listing they are fine.  Anybody know if there is a problem with the online map?

**Comment by DwaineGarden** [comment]
I also tried both the Android and IOS applications.   The maps don't update after the initial sensor is created.

**Comment by airbjorn** [comment]
I experience the same issue with my "hackAIR Home" sensor ID 7965d904b724d541b0b45ae6c9df1fa416ba1ab4d4c

**Comment by DwaineGarden** [comment]
I think something is broken with the map.   At least my measurements are there.

**Comment by sakisds** [comment]
Hello, the app/website team is not watching this repository so I am unable to help you. I suggest opening an issue in one of the other relevant repositories [here](https://github.com/hackair-project/), even if they don't have source code they are monitored by each project's team.

**Comment by wiebkehere** [comment]
I've passed the issue on to the app/website team.
