### ISSUE TITLE
[Wemos.ino] Send error and tamper fields to server

### ISSUE THREAD

**Issue by chris007de** [hackair-project/hackAir-Arduino#13]
In the current version of the Wemos.ino sketch, the `error` and `tamper` information in the JSON String is hardcoded to 0.

As there is currently no other error handling, sensor measurements of `0.00` (no sensor connected) or `NaN` (sensor reading failed, DHT reading failed, ...) are getting submitted with error=0 to the server, which shows that as `very_good` in the web interface (although the measurement csv has the correct `NaN` values inside).

**Comment by sakisds** [comment]
Versions >0.6.1 should send appropriate error messages for each failure. Notifications on the website is something that should be available in the future.
