### ISSUE TITLE
Definition of a more detailed error enum.

### ISSUE THREAD

**Issue by chris007de** [hackair-project/hackAir-Arduino#16]
As far as I can see, there are only two error states currenly (0 = good, 1 = error).
As there are some different reasons for an error, it might me usefule to differ between these reasons. The web interface could show the latest error codes, helping the sensor owner to solve issues.

It could look like this:
- E_ERR_UNSET = -1
- E_NOERR = 0
- E_UNDEFINED_ERROR = 1
- E_SENSOR_READ_TIMEOUT = 2
- E_TEMP_READ_FAIL = 3
- E_HUM_READ_FAIL = 4

**Comment by sakisds** [comment]
I had this on my TODO list, I will get in touch with the website team to see how they want to approach this.

**Comment by sakisds** [comment]
This is added in 4f64a07 and is available in versions >0.6.1.
