### ISSUE TITLE
Please change links to documentation

### ISSUE THREAD

**Issue by wiebkehere** [hackair-project/hackAir-Arduino#22]
The current version of the documentation is hosted here: http://www.hackair.eu/docs/

The old version at https://hackair-project.github.io/ should no longer be linked to.

**Comment by sakisds** [comment]
Hello, I changed the links to the new website in 040a529f46b3567705aa06dd8ac2a85c81f348a0. I also disabled the old Wiki, it is now at the `gh-pages-legacy` branch for archival.
